=== HaswanthTamil/devangar-polytechnic-college/frontend/src/app/content/schema/announcements.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "text",
            "position",
            "visible"
        ],
        "additionalProperties": false,
        "properties": {
            "text": {
                "type": "string",
                "minLength": 5
            },
            "link": {
                "type": "string"
            },
            "position": {
                "type": "integer",
                "minimum": 0
            },
            "visible": {
                "type": "boolean"
            }
        }
    }
}

=== HaswanthTamil/devangar-polytechnic-college/frontend/src/app/content/raw/announcements.json
[
  {
    "text": "STAFF WANTED:- EEE department, Qualification minimum B.E. , First class",
    "link": "",
    "position": 0,
    "visible": true
  },
  {
    "text": "Feedback facility of students and faculties available in AICTE web portal",
    "position": 2,
    "visible": true,
    "link": "/events/annual-day"
  }
]
