=== HaswanthTamil/devangar-polytechnic-college/frontend/src/app/content/schema/department-content.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "department",
            "image"
        ],
        "additionalProperties": false,
        "properties": {
            "department": {
                "type": "string",
                "enum": ["computer-engineering", "electrical-and-electronics-engineering", "electronics-and-communication-engineering", "mechanical-engineering", "civil-engineering"]
            },
            "name": {
                "type": "string",
                "enum": ["Computer Engineering", "Electrical and Electronics Engineering", "Electronics and Communication Engineering", "Mechanical Engineering", "Civil Engineering"]
            },
            "url": {
                "type": "string",
                "description": "Department URL"
            },
            "image": {
                "type": "string",
                "description": "Department featured image"
            }
        }
    }
}

=== HaswanthTamil/devangar-polytechnic-college/frontend/src/app/content/raw/department-content.json
[
  {
    "department": "electronics-and-communication-engineering",
    "image": "/images/uploads/ece.png",
    "url": "/departments/electronics-communication",
    "name": "Electronics and Communication Engineering"
  },
  {
    "department": "computer-engineering",
    "image": "/images/uploads/computer_eng.png",
    "url": "/departments/computer-engineering",
    "name": "Computer Engineering"
  },
  {
    "department": "civil-engineering",
    "image": "/images/uploads/civil.png",
    "url": "/departments/civil-engineering",
    "name": "Civil Engineering"
  },
  {
    "department": "mechanical-engineering",
    "image": "/images/uploads/mech.png",
    "url": "/departments/mechanical-engineering",
    "name": "Mechanical Engineering"
  },
  {
    "department": "electrical-and-electronics-engineering",
    "image": "/images/uploads/eee.png",
    "url": "/departments/electrical-electronics",
    "name": "Electrical and Electronics Engineering"
  }
]
